apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-migrations-sa
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upgrade-operator-sa
  namespace: default