apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        role VARCHAR(20) DEFAULT 'user',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    INSERT INTO users (username, email, password_hash, role) VALUES 
    ('admin', 'admin@dynamicsoft.hr', '$2a$10$example', 'admin'),
    ('john.doe', 'john@example.com', '$2a$10$example', 'user'),
    ('jane.smith', 'jane@example.com', '$2a$10$example', 'user')
    ON CONFLICT (username) DO NOTHING;